FROM node:12-alpine
RUN ["npm", "i", "-g", "@vue/cli"]

WORKDIR /usr/app
COPY ["*.js", "*.json", "src", "tests", "public", "/usr/app/"]
RUN ["npm", "i"]
ENV NODE_ENV=production
RUN ["npm", "run", "build"]
RUN ["npm", "prune"]

FROM nginx:alpine
WORKDIR /usr/app
COPY --from=0 /usr/app /usr/share/nginx/html/
